# Generated by Django 6.0.5 on 2026-06-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
